### heroes post
POST localhost:8081/api/heroes/
Content-Type: application/json

{
  "nombre" : "Lina Marcela ",
  "bio" : "mi hermosa novia",
  "img" : "la ms bonita",
  "aparicion" : "02/05/1993",
  "casa" : "De su casa"
}

### root
GET localhost:8081

### Prueba
GET localhost:8081/api/prueba

### multimedias
GET localhost:8081/api/multimedias

### auth
GET localhost:8081/api/auth

### heroes
GET localhost:8081/api/heroes

### heroes -> id
GET localhost:8081/api/heroes/1

### heroes como -> nombre
GET localhost:8081/api/heroes/como/nom

